server:
  port: 8092
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


#引入dubbo的配置
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user  #定义服务名称
  registry:              #定义注册中心链接
    address: zookeeper://192.168.52.130:2183?backup=192.168.52.130:2182,192.168.52.130:2184
